### ISSUE TITLE
Output seq and its length

### ISSUE THREAD

**Issue by mkazanov** [tjblaette/getitd#13] opened 2021-10-20 05:09 UTC
Dear Tamara,

If I understand correctly the final results of found ITDs are in file `itds_collapsed-is-same_is-similar_is-close_is-same_trailing_hc.tsv`.

This file contains the following data (below). Could you, please, explain it in more detail - although the specified length is 36 the sequence itself `TATGAATATGATCTCAAATGG` has a length 21. Why?

```
sample	length	start	vaf	ar	coverage	counts	trailing	seq	sense	external_bp	domains	start_chr13_bp	start_transcript_bp	start_protein_as	end_chr13_bp	end_transcript_bp	end_protein_as	insertion_site_chr13_bp	insertion_site_transcript_bp	insertion_site_protein_as	insertion_site_domain	file
test1	36	86	3.9326	0.040936	356	14	True	TATGAATATGATCTCAAATGG	{1}	0	['exon14_JMD_zipperMotif', 'exon14_JMD_hingeRegion']	28608267	1789	597	28608232	1824	608	28608231	1825	609	exon14_JMD_hingeRegion	['needle_21.txt', 'needle_20.txt', 'needle_23.txt']
```

Thank you in advance,
Marat

**Comment by tjblaette** [comment] 2021-10-20 08:36
Dear Marat,

that is the correct file, yes. The reason why the insert sequence in your example is shorter than the (predicted) full length of that ITD is that the ITD is "trailing" (see column 8 in your example file). This means that the read did not fully cover both tandems of the ITD - one was covered fully and one was covered partially. This latter part is the 21 bp sequence given in column 9, and based on the other tandem that *was* fully covered, getITD estimates the full length as 36 bp, as shown in column 2. 

You can find color-coded examples of a standard non-trailing as well as a trailing ITD in our paper, see Figure 1B: https://doi.org/10.1038/s41375-019-0483-z 

getITD also saves the exact alignment of each read and you can find respective filenames in the last column of your example. The three files 'needle_21.txt', 'needle_20.txt', 'needle_23.txt' in the getITD output folder will contain alignments just like those in Figure 1B of our paper, where you should be able to see that specific insert sequence and the adjacent 36 bp WT tandem.

I hope this makes sense, please let me know if not though!

All the best,
Tamara

**Comment by mkazanov** [comment] 2021-10-21 01:15
Hi Tamara,

thank you very much for your answer!
These 3 files are very useful for understanding, although I still have questions. I attached them below as well as screenshots.
I tried to highlight the repeats by the same colour (part that coincides with `TATGAATATGATCTCAAATGG` reported in the results by green, and other repeating sequences by yellow). 
As for me, these 3 files give different results. You can see the positions of insertion in the reference sequence are different in 3 files: 126 for needle_21, 127 for needle_20, and 121 for needle_23. So the results are inconsistent, right?
Do I understand correctly that the needle_23 have been chosen as the alignment for reporting results?
Is this because of the longest insertion?
Sorry if I don't understand something trivial, but I am still confused.

<img width="702" alt="Screen Shot 2021-10-21 at 04 17 14" src="https://user-images.githubusercontent.com/19509266/138193947-eff4d598-3e45-4556-bbe4-012430697fea.png">
<img width="690" alt="Screen Shot 2021-10-21 at 04 18 49" src="https://user-images.githubusercontent.com/19509266/138194086-8e9ac9a1-15fe-4ee6-9ae4-fd00aa8a2c14.png">
<img width="706" alt="Screen Shot 2021-10-21 at 04 00 58" src="https://user-images.githubusercontent.com/19509266/138193679-38eb0ac8-64c0-4dfe-b45f-8a3908a47cb3.png">
[needle_20.docx](https://github.com/tjblaette/getitd/files/7385194/needle_20.docx)
[needle_21.docx](https://github.com/tjblaette/getitd/files/7385195/needle_21.docx)
[needle_23.docx](https://github.com/tjblaette/getitd/files/7385196/needle_23.docx)

**Comment by tjblaette** [comment] 2021-10-22 08:09
Hi Marat,

you are absolutely correct. In fact, getITD will merge reads which have identical sequences, so as not to align the same (eg WT) read x million times. Only one alignment file will be created per unique sequence, so actually ALL the sequences in these needle files will be different from one another - though often the difference will be outside of the actual insert/ITD.

getITD goes through several steps at the end of an analysis to try and merge different reads which are likely supporting the same ITD - and this is where those intermediate output files come from. Have a look maybe at the output files from the example FASTQs that comes with getITD and see how things change from one merge step to the next. 

As for the criteria getITD uses for merging: It compares both the insert coordinates and the insert sequence. When those are identical, reads are merged into the same ITD (this step is easy). When coordinates are identical and the sequences are very similar, they are also merged (this is to account for sequencing errors in the insert, for example). When coordinates are very close to each other and sequences similar, they are also merged (this is to account for ambiguities in the alignment and sequencing errors that may appear to shift the insert). Since in these last two cases we are merging ITDs with different specifications, we have to choose one "representative" among them for the output file. For non-trailing ITDs this is the one with the highest read count; for trailing ITDs we choose the one with the longest insert. 


Hope this helps!
Tamara

**Comment by mkazanov** [comment] 2021-10-26 03:56
Hi Tamara,

thank you very much for your answer! Do I understand correctly that as these three merged sequences are different (needle_21, needle_20 and needle_23) and were mapped to the same reference sequence, then either the merging step for two out of three sequences was incorrect (or even for three of them) or the mapping to the reference sequence was incorrect? And we actually do not have confident knowledge of which alignment out of these three is correct, right? And there is even a possibility that all of them are incorrect and we even don't have FLT3-ITD insertion?

Thanks,
M.

**Comment by tjblaette** [comment] 2021-10-26 09:35
Hi Marat,

I don't think that's necessarily the right conclusion. Firstly, there will never be two needle* files which are the same. They each describe the alignment of a different read sequence, therefore are always different somehow. At the same time, the reference sequence will always be the same - all reads are aligned to the sequence provided in `-reference`. 

When I look at your three examples, I don't see how the alignment could be wrong (how else should getITD have aligned these examples?). I also clearly see an insertion in each one, which also clearly resembles some part of the preceding WT sequence. Therefore, all three look like proper ITDs to me. Now when I compare the three inserts, they clearly are also quite similar, as you have also highlighted. getITD concludes that these sequences are so similar, they are likely describing the same ITD. Looking at them manually, I'm not sure that's right, as there are also clear differences that don't look like they can be explained by simple sequencing errors.

So my conclusion would be: Your three insertions are clearly ITDs, but the merging may be incorrect.

Do you find similar ITDs/insertions such as these three in many of your samples? That could be an indication of a PCR/assay artefact. 

The other thing I noticed is that your reads seems to start a bit earlier than ours do. Are you using an amplicon-based assay similar to ours or is this data from hybridization capture? It won't change anything for these three trailing inserts, but if this is amplicon-based, and all your reads start this early, you can help getITD by extending your reference sequence: Add the "ATCTCTGAAG" to amplicon.txt, adjust the primer sequences in primers.txt, and expand the annotation in amplicon_kayser,tsv (add one line per additional nucleotide that you added to amplicon.txt).

All the best,
Tamara

**Comment by mkazanov** [comment] 2021-10-26 14:52
Hi Tamara, 

Thank you for your answer! There is something that I don't understand. The reference sequence is a unique part of the FLT3 gene, right? If so, how three (not only single) ITDs concurrently can be proper ITDs, as you wrote, if there is only a single reference sequence? Sorry, possibly I don't understand something trivial.

**Comment by tjblaette** [comment] 2021-10-28 10:39
Hi Marat,

Yes, the reference sequence is a subsequence of the FLT3 gene. 

We can still detect more than one true ITD in a certain sample because we are performing bulk sequencing (unless you are doing single-cell sequencing?). When we sequence the DNA from multiple cells, even from the same patient, these may carry different mutations (i.e. tumors are genetically heterogeneous and the same type of mutation may arise independently in different cells of the same patient). The clinical gold standard for ITD detection, capillary-electrophoresis-based fragment analysis, can also multiple different clones/mutations per sample (often 2, rarely 3). Due to its much higher sensitivity, getITD can pick up many more than that. To be honest, this was the most interesting and surprising finding for me during our validation experiments: We found patients with up to 16 different ITD clones in the same sample. And we believe these are true, as they were reproducible across independent preps of the same sample, independent preps of bone marrow vs peripheral blood from the same patient, and independent preps of a patient's samples from diagnosis, (clinical) remission and relapse. I guess we just never knew this massive heterogeneity was there until we had the tools to go look for it.

Something we did not really see during our validation experiment though were recurrent ITDs that appear in many different patients. These are generally a sign of artefacts or contamination. So differnet ITDs in the same patient are ok; the same ITD in different patients can be problematic. 

Have you looked at our publication? It includes more detail on many of these findings and may be helpful to read.

Let me know if that helps,
Tamara

**Comment by mkazanov** [comment] 2021-10-30 10:59
Dear Tamara,

thank you very much for your answer! This is very interesting and exciting information (multiple clones in single sample)! Please, close this issue. I will write to you directly if you don't mind, later when we analyzed more samples with conformed ITD (fragment analysis) and control.

**Comment by tjblaette** [comment] 2021-11-01 07:29
Perfect, I'm glad I could help!

**Closed as completed by tjblaette** 2021-11-01 07:29 UTC
